title: Here is some stuff about eli.
description: > # this means to ignore newlines until "baseurl:"
 This is a personal website for Eli Neiburger. The alternative was updating my linkedin, gross!
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://elitrichous.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: elitrichous

# Author Settings
author: eli neiburger # add your name
author-img: david-freeman.jpg # add your photo
about-author: Seeking employment as the director of the Ann Arbor District Library. # add description
social-twitter: @elitrichous # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: elitrichous # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: eli@eliworks.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
